name: '[test] check schema'

on: [push]
jobs:
  check_schema:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: checkout siibra
      uses: actions/checkout@v4
      with:
        repository: FZJ-INM1-BDA/siibra-python
        path: ../siibra-python
        fetch-depth: 1
        clean: True
        ref: 'main'

    - name: Install requirements
      run: pip install -r ../siibra-python/config_schema/requirements.txt
  
    - name: check schema
      run: python ../siibra-python/config_schema/check_schema.py ./
