name: '[test] test configuration'

on:
  push:
    paths:
    - 'maps/**.json'

jobs:
  check_maps_precompmesh:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'maps/**.json')
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements
      run: |
          pip install -U pip
          pip install -r _ci/requirements.txt
    - name: Check precomputed mesh
      run: python _ci/check_precompmesh.py
