name: '[test] check schema'

on: [push]
jobs:
  check_schema:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: checkout siibra
      env:
        SIIBRA_PYTHON_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/siibra-python
        SIIBRA_PYTHON_BRANCH: main
      uses: actions/checkout@v4
      with:
        repository: FZJ-INM1-BDA/siibra-python
        path: '$SIIBRA_PYTHON_PATH'
        fetch-depth: 1
        clean: True

    - name: Install requirements
      run: pip install -r $SIIBRA_PYTHON_PATH/config_schema/requirements.txt
  
    - name: check schema
      run: python $SIIBRA_PYTHON_PATH/config_schema/check_schema.py $PWD
