name: '[test] check region id uniqueness'

on:
  push:
    paths:
    - 'parcellations/**.json'

jobs:
  check_region_id_uniqueness:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: checkout siibra-python
      uses: actions/checkout@v4
      with:
        repository: FZJ-INM1-BDA/siibra-python
        path:  siibra-python-${{ github.run_id }}-${{ github.run_number }}
        fetch-depth: 1
        clean: True
        ref: 'main'
    
    - name: move siibra-python one up from workspace
      run: mv siibra-python-${{ github.run_id }}-${{ github.run_number }} ../siibra-python
    
    - name: Install siibra-python testing requirements
      run: |
          pip install -r ../siibra-python/requirements-test.txt
          pip install -r ../siibra-python/requirements.txt
    
    - name: region id uniqueness test
      run: |
        export SIIBRA_USE_CONFIGURATION='./'
        pytest ../siibra-python/e2e/core/test_parcellation.py::test_parc_id_uniqueness
        pytest ../siibra-python/e2e/core/test_parcellation.py::test_region_id_uniqueness