name: '[mirror] push to mirror'

on:
  push:
    branches: ["master"]
    tags: ["**"]

jobs:
  # n.b. we use access token, rather than https://github.com/valtech-sd/git-sync
  # because it does not seem possible to add project wide ssh key
  # and using personal key is not very flesible
  push_to_mirror:
    if: ${{ vars.EBRAINS_GITLAB_HOST != '' }}
    runs-on: ubuntu-latest
    environment: gitlab_mirror
    steps:
    - name: before script
      run: |
        'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        eval $(ssh-agent -s)
        git config --global user.email "inm1-bda@fz-juelich.de"
        git config --global user.name "inm1 bda - gitlab bot"
        mkdir -p ~/.ssh
        ssh-keyscan ${{ vars.EBRAINS_GITLAB_HOST }} >> gitlab-known-hosts
        cat gitlab-known-hosts >> ~/.ssh/known_hosts

    - name: script
      run: |
        git fetch --tags -f
        git fetch origin master
        if ! git ls-remote ebrains > /dev/null; then git remote add ebrains https://jugitpusher:${{ secrets.EBRAINS_GITLAB_PUSH_TOKEN }}@${{ vars.EBRAINS_GITLAB_HOST }}/${{ secrets.GITLAB_MIRROR_REPO_PATH }}; fi
        git push ebrains --tags -f
        git push ebrains HEAD:master -f 
