name: '[ci/cd] restart data validation VM'

on:
  push:
    branches:
      - "master"
  workflow_run:
    types: [completed]
    workflows: ['[test] test configuration']
  workflow_dispatch:

jobs:
  restart-data-validation:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.runner == 'siibra-data-validation' }}
    steps:
    - run: |
        echo "This job runs only if the runner is 'siibra-data-validation'."
    # runs-on: siibra-data-validation
    # steps:
    # - run: |
    #     /bin/bash -c "cd /softwares/software && ./restart.sh"
