name: '[ci/cd] restart data validation VM'

on:
  push:
    branches:
      - "master"
  workflow_run:
    types: [completed]
    workflows: ['[test] test configuration']
  workflow_dispatch:

jobs:
  restart-data-validation:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.runner }} == "siibra-data-validation"
    steps:
    - run: |
        echo ""
    # data validation will be enabled in the future when the runner is available.
    # runs-on: siibra-data-validation
    # steps:
    # - run: |
    #     /bin/bash -c "cd /softwares/software && ./restart.sh"
